### ISSUE TITLE
imshow gtk2 error on linux

### ISSUE THREAD

**Issue by extraymond** [conda-forge/opencv-feedstock#43]
After installing opencv from conda-forge, I'm able to import cv2 and use most of cv2's function.
But when trying to imshow after imread, I got an error suggesting I have built time problems.

error message below
--------------------------------------------

> **error**                                     Traceback (most recent call last)
<ipython-input-7-4ebda984245d> in <module>()
----> 1 cv2.imshow('hi',img)
**error**: /feedstock_root/build_artefacts/work/opencv-3.1.0/modules/highgui/src/window.cpp:545: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

**Comment by extraymond** [comment]
And I do have these packages installed in my setup.

**Comment by sdvillal** [comment]
In order to maintain compatibility, conda-forge opencv builds without gtk2 support (see #25 ). We have a [conda-forge based recipe](https://github.com/loopbio/opencv-feedstock) that builds with ffmpeg and gtk2 support on linux. You might want to use it to build your own opencv package, or you could use our prebuilt packages:

```sh
conda install -c loopbio ffmpeg-feature gtk2-feature opencv
```

Note that this last option installs, at the moment, our conda gtk2 package. You can remove it afterwards if you prefer to use your system's gtk2.

**Comment by extraymond** [comment]
Thx, I tried the prebuilt packages too, and it still gives me the same error.

**Comment by sdvillal** [comment]
Maybe the package did not update to that in our our channel. What does 
```conda list | grep opencv``` say?

**Comment by extraymond** [comment]
It says this 
`opencv                   3.1.0               np111py35_1`
I think it's the latest in loopbio repo!
I have tried several opencv packages in conda repos, conda-forge, menpo and loopbio, all without success.

**Comment by sdvillal** [comment]
No, that was not coming from the loopbio repo. In fact we had not build the package for python 3. I have just uploaded the [corresponding packages](https://anaconda.org/loopbio/opencv/files) for python 3.x + numpy 1.11. Let me know if you need something different.

If you succeed, you should see a line like this after running ```conda list```:
```opencv                    3.1.0           np111py36_ffmpeg_gtk2_1  [ffmpeg gtk2]  loopbio```

**Comment by jakirkham** [comment]
Actually I think I might be ok adding support for things like `ffmpeg` and possibly `gtk2` to conda-forge's `opencv`. We should probably do them one at a time. Would you be interested in doing a PR, @sdvillal?

**Comment by zym1010** [comment]
@sdvillal Hi I tried your gtk2-enabled opencv to compile Caffe. However, it complains that `libopencv_highgui.so: undefined reference to `gtk_widget_set_realized'`. Any idea? Thanks.

**Comment by zym1010** [comment]
@sdvillal is the case that your opencv doesn't come with its own gtk? I think this is the case after examining the actual files.

**Comment by sdvillal** [comment]
I'm using [conda features](https://conda.io/docs/building/meta-yaml.html#id2) to manage opencv, so if you want the gtk2 version, you need to install a package tracking the gtk2 feature. I know it is not very intuitive, but that is as good as it gets with conda right now.

In our repo we have two packages that track the gtk2 feature: ```gtk2-feature``` does not install anything and let you use your system gtk2. ```gtk2``` does install gtk2. On top of that, you also need the "ffmpeg" feature if you want our opencv to be selected.

We are also packaging caffe. The following *environment.yaml* will create you an environment with opencv 3.2.0 compiled with gtk2 and ffmpeg support plus caffe compiled with cuda support. Note that cuda is not packaged, so you need to have it installed in your system (you get some hints on how to do so after the environment is created).

```yaml
name: caffecv
channels:
  - loopbio      # gtk2-feature, gtk2, ffmpeg-feature,
                 # opencv [gtk2, ffmpeg]
                 # cuda-feature, cudnn-feature, caffe [cuda, cudnn],
  - conda-forge  # everything else
  - pkgw-forge   # atk gdk2-pixbuf & deps
  - defaults     # in case anything is missing

dependencies:
  - python

  # Image proc libs
  - gtk2            # for opencv (needed by loopb); will use system gtk2
  - ffmpeg-feature  # for opencv (kinda needed by loopb)
  - ffmpeg
  - opencv

  # Caffe-GPU
  - cuda-feature
  - cudnn-feature
  - caffe-cuda

  # Caffe-CPU
  # - caffe
```

Install, activate, list it like
```sh
conda env create -f environment.yaml
source activate caffecv
conda list
```

If everything has worked well, you should see lines like these in the package list
```
caffe-cuda                1.0.0rc5_8.0_5.1 cuda8.0_cudnn5.1_0  [cuda8.0 cudnn5.1]  loopbio
opencv                    3.2.0           np112py36_ffmpeg_gtk2_1  [ffmpeg gtk2]  loopbio
```

If you have more questions, feel free to open an issue in our [opencv recipe repo](https://github.com/loopbio/opencv-feedstock). I think it is best to continue there the conversation.
